buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.77.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'sls-packaging'
include 'gradle-sls-packaging'
include 'gradle-sls-packaging-api'
include 'gradle-recommended-product-dependencies'
throw new RuntimeException('''The excavator failed to run properly - exited with code 1 and output:\n\n''' + file('gradle/exception').text + '\n\n')
